apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dyzvi5c18-nodejs 
  janus-idp.io/tekton: dyzvi5c18-nodejs
  backstage.io/kubernetes-id: dyzvi5c18-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dyzvi5c18-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  