apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dyzvi5c18-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:a9662c9b9ae31c75e9eecdae0b7bc7b8d8c11730@sha256:6af3cf05824ff25022b4bda69410f62f51c71f5fcd26ef44913da0b1aa39f675
          name: container-image
